parameters:
    imbc.form.type.multiselect.class:              Imbc\WebsiteBundle\Form\Type\MultiSelectType
    imbc.form.type.chosen.class:              Imbc\WebsiteBundle\Form\Type\ChosenType
    imbc.notification.class:                  Imbc\WebsiteBundle\Controller\NotificationController
    imbc.twig.notification_extension.class: Imbc\WebsiteBundle\Twig\Extension\NotificationExtension

services:

    imbc.notify:
        class: %imbc.notification.class%
        arguments:
            session: '@session'
            defaults:
                message: '%imbc.notify.message%'
                title: '%imbc.notify.title%'
                class: '%imbc.notify.class%'
                type: '%imbc.notify.type%'
                lifetime: '%imbc.notify.lifetime%'
                click_to_close: '%imbc.notify.click_to_close%'

    imbc.twig.message_extension:
        class: %imbc.twig.notification_extension.class%
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    imbc.form.type.multiselect:
        class: %imbc.form.type.multiselect.class%
        tags:
            - { name: form.type, alias: imbc_multiselect }

    imbc.form.type.chosen:
        class: %imbc.form.type.chosen.class%
        tags:
            - { name: form.type, alias: imbc_chosen }

    imbc.form.type.daterange:
        class: %imbc.form.type.multiselect.class%
        tags:
            -  { name: form.type, alias: multiselect }